/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurants_manager;

import DataBaseConn.sqldatabaseconn;
import java.awt.ComponentOrientation;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class Add_New_Transaction extends javax.swing.JFrame {
    
    
    
    

    /**
     * Creates new form Search_and_Add_Deliviry
     */
    public Add_New_Transaction(String supplier_name, String supplier_phone,String supplier_company,String supplier_hint ) {
         this.setAlwaysOnTop(true);
         this.setUndecorated(true);
         this.setVisible(true);
         this.setResizable(false);
         initComponents();
         
//         Toolkit t = Toolkit.getDefaultToolkit();
//         int wid = (int) t.getScreenSize().getWidth();
//         int hid = (int) t.getScreenSize().getHeight();
//          this.setSize(wid , hid);
       //  this.setSize(1360 , 768);
         // this.pack();
      //   this.setLocationRelativeTo(null);
         // this.setLocation(wid/2-this.getSize().width/2, hid/2-this.getSize().height/2);
         
          Frame_Size frame_Size = new Frame_Size();
         this.setSize(frame_Size.width(),frame_Size.height());
         
         jTextField_supplier_name.setText(supplier_name);
         jTextField_supplier_phone.setText(supplier_phone);
         jTextField_supplier_company.setText(supplier_company);
         jTextField_supplier_hint.setText(supplier_hint);
     
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_supplier_name = new javax.swing.JTextField();
        jTextField_supplier_hint = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_supplier_phone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_supplier_company = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_type_of_goods = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_he_want = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_i_want = new javax.swing.JTextField();
        jTextField_transaction_hint = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_transaction_date = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_error = new javax.swing.JLabel();
        jButton_new_Supplier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(15, 15, 15));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setText("_");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 0), null));
        jPanel3.setToolTipText("");

        jLabel2.setBackground(new java.awt.Color(51, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("أسم المورد :");

        jTextField_supplier_name.setEditable(false);
        jTextField_supplier_name.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_supplier_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_supplier_name.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_supplier_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_supplier_name.setToolTipText("");
        jTextField_supplier_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_supplier_nameKeyReleased(evt);
            }
        });

        jTextField_supplier_hint.setEditable(false);
        jTextField_supplier_hint.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_supplier_hint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_supplier_hint.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_supplier_hint.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_supplier_hint.setToolTipText("");
        jTextField_supplier_hint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_supplier_hintActionPerformed(evt);
            }
        });
        jTextField_supplier_hint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_supplier_hintKeyReleased(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(51, 0, 0));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ملحوظة عن المورد :");

        jTextField_supplier_phone.setEditable(false);
        jTextField_supplier_phone.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_supplier_phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_supplier_phone.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_supplier_phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_supplier_phone.setToolTipText("");
        jTextField_supplier_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_supplier_phoneKeyReleased(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(51, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("الهاتف :");

        jLabel4.setBackground(new java.awt.Color(51, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("اسم الشركة :");

        jTextField_supplier_company.setEditable(false);
        jTextField_supplier_company.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_supplier_company.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_supplier_company.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_supplier_company.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_supplier_company.setToolTipText("");
        jTextField_supplier_company.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_supplier_companyKeyReleased(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(51, 0, 0));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("نوع البضاعة :");

        jTextField_type_of_goods.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_type_of_goods.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_type_of_goods.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_type_of_goods.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_type_of_goods.setToolTipText("");
        jTextField_type_of_goods.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_type_of_goodsKeyReleased(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(51, 0, 0));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("مدين (له) :");

        jTextField_he_want.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_he_want.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_he_want.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_he_want.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_he_want.setToolTipText("");
        jTextField_he_want.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_he_wantKeyReleased(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(51, 0, 0));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("دائن(عليه) :");

        jTextField_i_want.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_i_want.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_i_want.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_i_want.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_i_want.setToolTipText("");
        jTextField_i_want.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_i_wantKeyReleased(evt);
            }
        });

        jTextField_transaction_hint.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_transaction_hint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_transaction_hint.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_transaction_hint.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_transaction_hint.setToolTipText("");
        jTextField_transaction_hint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_transaction_hintActionPerformed(evt);
            }
        });
        jTextField_transaction_hint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_transaction_hintKeyReleased(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(51, 0, 0));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ملحوظة عن التعامل :");

        jTextField_transaction_date.setEditable(false);
        jTextField_transaction_date.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_transaction_date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_transaction_date.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_transaction_date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_transaction_date.setToolTipText("");
        jTextField_transaction_date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_transaction_dateKeyReleased(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(51, 0, 0));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("تاريخ التعامل :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_transaction_hint, javax.swing.GroupLayout.PREFERRED_SIZE, 1423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jTextField_supplier_company, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_supplier_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_supplier_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jTextField_transaction_date, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jTextField_i_want, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_he_want, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_type_of_goods, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addComponent(jTextField_supplier_hint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_supplier_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_supplier_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_supplier_company, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_supplier_hint, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_type_of_goods, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_he_want, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_i_want, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField_transaction_date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_transaction_hint, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel10.setBackground(new java.awt.Color(51, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Safi_restaurants_manager/pics/add_new_trans_icon.png"))); // NOI18N
        jLabel10.setText("اضافة تعامل جديد");
        jLabel10.setToolTipText("");

        jLabel_error.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_error.setForeground(new java.awt.Color(153, 0, 0));
        jLabel_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_error.setToolTipText("");

        jButton_new_Supplier.setBackground(new java.awt.Color(0, 153, 51));
        jButton_new_Supplier.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_new_Supplier.setForeground(new java.awt.Color(255, 255, 255));
        jButton_new_Supplier.setText("حفظ التعامل");
        jButton_new_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_new_SupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_new_Supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGap(55, 55, 55)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(jLabel_error, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_new_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int rowcount =0;

int id ;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.setVisible(false);
   //  new Takeaway_jframe().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
     
 
     jTextField_supplier_name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
     jTextField_supplier_company.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    
     jLabel_error.setText("");
     
     DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        jTextField_transaction_date.setText(dtf.format(now));
     
    
 
       
    }//GEN-LAST:event_formWindowActivated

    private void jTextField_supplier_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_supplier_nameKeyReleased
    
    }//GEN-LAST:event_jTextField_supplier_nameKeyReleased

    private void jTextField_supplier_phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_supplier_phoneKeyReleased
    }//GEN-LAST:event_jTextField_supplier_phoneKeyReleased

    private void jTextField_supplier_companyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_supplier_companyKeyReleased
    }//GEN-LAST:event_jTextField_supplier_companyKeyReleased

    private void jTextField_supplier_hintKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_supplier_hintKeyReleased
    }//GEN-LAST:event_jTextField_supplier_hintKeyReleased

    private void jButton_new_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_new_SupplierActionPerformed
       
        String supplier_name = jTextField_supplier_name.getText();
        String supplier_phone =  jTextField_supplier_phone.getText();
        String supplier_company = jTextField_supplier_company.getText();       
        String supplier_hint =  jTextField_supplier_hint.getText();
        String type_of_goods =  jTextField_type_of_goods.getText();
        String he_want =  jTextField_he_want.getText();
        String i_want =  jTextField_i_want.getText();
        String transaction_date =  jTextField_transaction_date.getText();
        String transaction_hint =  jTextField_transaction_hint.getText();
       

      

        if(!supplier_name.equals("")&&!supplier_phone.equals("")&&!supplier_company.equals("")&&!supplier_hint.equals("")&&
           !type_of_goods.equals("")&&!he_want.equals("")&&!i_want.equals("")&&!transaction_date.equals("")&&!transaction_hint.equals("")&&test_num(i_want)&&test_num(he_want)){

            sqldatabaseconn add_supplier_dealings = new sqldatabaseconn();
            add_supplier_dealings.insert_supplier_dealings("supplier_dealings", supplier_name, supplier_phone, supplier_company, supplier_hint, type_of_goods, he_want, i_want, transaction_date, transaction_hint);
            jTextField_supplier_name.setText("");
            jTextField_supplier_phone.setText("");
            jTextField_supplier_company.setText("");          
            jTextField_supplier_hint.setText(""); 
            jTextField_type_of_goods.setText("");
            jTextField_he_want.setText("");
            jTextField_i_want.setText("");
            jTextField_transaction_date.setText("");
            jTextField_transaction_hint.setText("");
            jLabel_error.setText("تم حفظ جميع البيانات ");
            
        }
        else{
            jLabel_error.setText("ادخل جميع البيانات بطريقه صحيحة و تحقق من عدم كتابه حروف فى خانات الأرقام");
        }
    }//GEN-LAST:event_jButton_new_SupplierActionPerformed

    private void jTextField_supplier_hintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_supplier_hintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_supplier_hintActionPerformed

    private void jTextField_type_of_goodsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_type_of_goodsKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_type_of_goodsKeyReleased

    private void jTextField_he_wantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_he_wantKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_he_wantKeyReleased

    private void jTextField_i_wantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_i_wantKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_i_wantKeyReleased

    private void jTextField_transaction_hintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_transaction_hintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_transaction_hintActionPerformed

    private void jTextField_transaction_hintKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_transaction_hintKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_transaction_hintKeyReleased

    private void jTextField_transaction_dateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_transaction_dateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_transaction_dateKeyReleased
   
    
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_New_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_New_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_New_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_New_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_New_Transaction("", "", "", "").setVisible(true);
            }
        });
    }
    
      private boolean test_num(String text) {
      try {
         Integer.parseInt(text);
         return true;
      } catch (NumberFormatException e) {
         return false;
      }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_new_Supplier;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_error;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField_he_want;
    private javax.swing.JTextField jTextField_i_want;
    private javax.swing.JTextField jTextField_supplier_company;
    private javax.swing.JTextField jTextField_supplier_hint;
    private javax.swing.JTextField jTextField_supplier_name;
    private javax.swing.JTextField jTextField_supplier_phone;
    private javax.swing.JTextField jTextField_transaction_date;
    private javax.swing.JTextField jTextField_transaction_hint;
    private javax.swing.JTextField jTextField_type_of_goods;
    // End of variables declaration//GEN-END:variables
}
