/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurants_manager;

import DataBaseConn.sqldatabaseconn;
import java.awt.ComponentOrientation;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author root
 */
public class Add_Costmer_Deliviry extends javax.swing.JFrame {

    /**
     * Creates new form Add_Costmer_Deliviry
     */
    public Add_Costmer_Deliviry() {
     //   this.setAlwaysOnTop(true);
         this.setUndecorated(true);
         this.setVisible(true);
         this.setResizable(false);
         initComponents();
         
//         Toolkit t = Toolkit.getDefaultToolkit();
//         int wid = (int) t.getScreenSize().getWidth();
//         int hid = (int) t.getScreenSize().getHeight();

         Frame_Size frame_Size = new Frame_Size();
         this.setSize(frame_Size.width(),frame_Size.height());
        
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel_error = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_customer_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_customer_phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_customer_address = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_customer_floor = new javax.swing.JTextField();
        jTextField_customer_aprtment_num = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_allaria_cost = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField_addnew_ariacost = new javax.swing.JTextField();
        jTextField_addnew_aria = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel_aria_added = new javax.swing.JLabel();
        jButton_addnewaria_save = new javax.swing.JButton();
        jTextField_chosen_cost = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_chosen_aria = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_customer_know_sign = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1600, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(15, 15, 15));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setToolTipText("");

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("أضافة + طلب");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("أضافة فقط");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setText("_");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 0), null));
        jPanel3.setToolTipText("");

        jLabel_error.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_error.setForeground(new java.awt.Color(102, 0, 0));
        jLabel_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_error.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("الأسم :");

        jTextField_customer_name.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_customer_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_customer_name.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_customer_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_customer_name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_customer_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_customer_nameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("رقم الهاتف المحمول :");

        jTextField_customer_phone.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_customer_phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_customer_phone.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_customer_phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_customer_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_customer_phoneActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("العنوان :");

        jTextField_customer_address.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_customer_address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_customer_address.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_customer_address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_customer_address.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_customer_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_customer_addressActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("رقم الدور:");

        jTextField_customer_floor.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_customer_floor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_customer_floor.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_customer_floor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_customer_aprtment_num.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_customer_aprtment_num.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_customer_aprtment_num.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_customer_aprtment_num.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("رقم الشقه :");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("المنطقة و خدمه التوصيل :");

        jComboBox_allaria_cost.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_allaria_cost.setEditable(true);
        jComboBox_allaria_cost.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_allaria_cost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "أختر المنطقة" }));
        jComboBox_allaria_cost.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_allaria_costItemStateChanged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setToolTipText("");

        jLabel21.setBackground(new java.awt.Color(0, 51, 51));
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("<html><center> أذا كانت المنطقه الخاصه بالعميل غير مسجله بقائمة (المنطقة) <br>الرجاء أضافه منطقه جديده هنا مع تكلفه خدمة التوصيل .</center></html>");
        jLabel21.setToolTipText("");

        jTextField_addnew_ariacost.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_addnew_ariacost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_addnew_ariacost.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_addnew_ariacost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_addnew_ariacost.setText("0");

        jTextField_addnew_aria.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_addnew_aria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_addnew_aria.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_addnew_aria.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("أسم المنطقة :");
        jLabel22.setToolTipText("");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("تكلفة التوصيل :");
        jLabel23.setToolTipText("");

        jLabel_aria_added.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_aria_added.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_aria_added.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton_addnewaria_save.setBackground(new java.awt.Color(0, 153, 0));
        jButton_addnewaria_save.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton_addnewaria_save.setForeground(new java.awt.Color(255, 255, 255));
        jButton_addnewaria_save.setText("أضافه منطقة جديدة");
        jButton_addnewaria_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addnewaria_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_addnewaria_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addComponent(jTextField_addnew_ariacost, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel_aria_added, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jTextField_addnew_aria)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel22))))
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator4)
                        .addGap(34, 34, 34))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_aria_added, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_addnew_ariacost, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_addnew_aria, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_addnewaria_save, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jTextField_chosen_cost.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_chosen_cost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_chosen_cost.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_chosen_cost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_chosen_cost.setText("0");
        jTextField_chosen_cost.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("تكلفة التوصيل :");

        jTextField_chosen_aria.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_chosen_aria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_chosen_aria.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_chosen_aria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_chosen_aria.setToolTipText("");
        jTextField_chosen_aria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_chosen_ariaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("المنطقة التي تم أختيارها :");

        jTextField_customer_know_sign.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_customer_know_sign.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_customer_know_sign.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_customer_know_sign.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_customer_know_sign.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("علامه مميزه :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_customer_phone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_customer_aprtment_num, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_customer_floor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addComponent(jTextField_customer_address)))
                    .addComponent(jTextField_customer_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField_chosen_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_chosen_aria, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField_customer_know_sign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addComponent(jComboBox_allaria_cost, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_customer_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_customer_floor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_customer_aprtment_num, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_customer_address, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_allaria_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_chosen_aria, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jTextField_chosen_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_customer_know_sign, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jLabel_error, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Safi_restaurants_manager/pics/add_costmer_icon.png"))); // NOI18N
        jLabel5.setText("أضافه عميل");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(20, 20, 20)
                        .addComponent(jButton1))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 Statement s ;
     ResultSet r ;
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     jTextField_customer_name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
     jTextField_customer_address.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
     jTextField_customer_know_sign.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
     jLabel_error.setText("");
     
     sqldatabaseconn conn = new sqldatabaseconn();
     Statement s ;
     ResultSet r ;
     try{
       s =conn.connect().createStatement(ResultSet.TYPE_FORWARD_ONLY,ResultSet.CONCUR_READ_ONLY);
             r =s.executeQuery("select * from aria_and_cost");
           
            
             while(r.next()){
             String aria = r.getString("aria");
             int cost = r.getInt("cost");
             String all_aria_cost = aria+" "+cost ;
             jComboBox_allaria_cost.addItem(all_aria_cost);            
             }
     }
     catch(Exception e)
     {System.out.println(e);}
     
    }//GEN-LAST:event_formWindowActivated

    private void jTextField_customer_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_customer_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_customer_addressActionPerformed

    private void jTextField_chosen_ariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_chosen_ariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_chosen_ariaActionPerformed

    private void jComboBox_allaria_costItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_allaria_costItemStateChanged

        int index = jComboBox_allaria_cost.getSelectedIndex();
        
        
        if(index == 0){
            jTextField_addnew_aria.setEnabled(true);
             jTextField_addnew_ariacost.setEnabled(true);
             jButton_addnewaria_save.setEnabled(true);
 
        }else{
            jTextField_addnew_aria.setEnabled(false);
             jTextField_addnew_ariacost.setEnabled(false);
             jButton_addnewaria_save.setEnabled(false);
        }

        sqldatabaseconn conn = new sqldatabaseconn();
        try{
            s =conn.connect().createStatement(ResultSet.TYPE_FORWARD_ONLY,ResultSet.CONCUR_READ_ONLY);
            r =s.executeQuery("select * from aria_and_cost WHERE _id = "+index);
            r.next();
            String aria= r.getString("aria");
            int cost = r.getInt("cost");
            String costs = Integer.toString(cost);
            jTextField_chosen_aria.setText(aria);
            jTextField_chosen_cost.setText(costs);
            

        }
        catch(Exception e){System.out.println(e);}
        finally {
            if(r != null){
                try{
                    r.close();        
                } catch(Exception e){                 
                }
            }
            if(conn != null){
                try{
                    conn.connect().close();
                } catch(Exception e){
                }
            }
        }

    }//GEN-LAST:event_jComboBox_allaria_costItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     this.setVisible(false);
    // new Takeaway_jframe().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton_addnewaria_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addnewaria_saveActionPerformed

        int cost = 0 ;
        String aria= jTextField_addnew_aria.getText();
        try{
            cost = Integer.parseInt(jTextField_addnew_ariacost.getText());
        }
        catch(Exception e){jLabel_aria_added.setText("لقد أدخلت حروف في خانة التكلفة ...!");}
        if(aria.equals("")||cost==0)
        {
            jLabel_aria_added.setText("أدخل بيانات المنطقه...!");
        }
        else{
            sqldatabaseconn add_Aria = new sqldatabaseconn();
            add_Aria.insert_Aria("aria_and_cost",aria,cost);
            jLabel_aria_added.setText("تم تسجيل منطقه جديده");
            jComboBox_allaria_cost.setSelectedIndex(0);
            jTextField_chosen_aria.setText(aria);
            jTextField_chosen_cost.setText(jTextField_addnew_ariacost.getText());
            jTextField_addnew_aria.setText("");
            jTextField_addnew_ariacost.setText("0");
        }
        
    }//GEN-LAST:event_jButton_addnewaria_saveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String costmer_name =       jTextField_customer_name.getText();
        String costmer_mobile =      jTextField_customer_phone.getText();
        String cus_home_phone = jTextField_customer_phone.getText();
        String costmer_address =    jTextField_customer_address.getText();
        String aprt_num =  jTextField_customer_aprtment_num.getText();
        String floor =      jTextField_customer_floor.getText();
        String know_sign =       jTextField_customer_know_sign.getText();
        String aria =       jTextField_chosen_aria.getText();
        String aria_cost =      jTextField_chosen_cost.getText();

        int aria_costn = Integer.parseInt(aria_cost);
        
        if(!costmer_name.equals("")&&!costmer_mobile.equals("")&&!costmer_address.equals("")&&!aprt_num.equals("")&&
   !floor.equals("")&&!aria.equals("")&&!know_sign.equals("")&&!aria_cost.equals("")){

        sqldatabaseconn add_customer = new sqldatabaseconn();
        add_customer.insert_costmer_data("add_costmerdelivir", costmer_name, costmer_mobile, cus_home_phone, costmer_address, floor, aprt_num, know_sign, aria, aria_costn);
        jTextField_customer_name.setText("");
        jTextField_customer_phone.setText("");
        jTextField_customer_phone.setText("");
        jTextField_customer_address.setText("");
        jTextField_customer_aprtment_num.setText("");
        jTextField_customer_floor.setText("");
        jTextField_customer_know_sign.setText("");
        jTextField_chosen_aria.setText("");
        jTextField_chosen_cost.setText("");
        jLabel_error.setText("تم أدخال جميع البيانات ");
        }
        else{
jLabel_error.setText("أدخل جميع البيانات المطلوبة......!");
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String costmer_name = jTextField_customer_name.getText();
        String costmer_mobile =  jTextField_customer_phone.getText();
        String costmer_address = jTextField_customer_address.getText();
        String aprt_num =  jTextField_customer_aprtment_num.getText();
        String floor =  jTextField_customer_floor.getText();
        String aria =  jTextField_chosen_aria.getText();
        String know_sign =   jTextField_customer_know_sign.getText();
        String aria_cost =  jTextField_chosen_cost.getText();

if(!costmer_name.equals("")&&!costmer_mobile.equals("")&&!costmer_address.equals("")&&!aprt_num.equals("")&&
   !floor.equals("")&&!aria.equals("")&&!know_sign.equals("")&&!aria_cost.equals("")){

        int aria_costn = Integer.parseInt(aria_cost);

        sqldatabaseconn add_customer = new sqldatabaseconn();
        add_customer.insert_costmer_data("add_costmerdeliviry", costmer_name, costmer_mobile, costmer_mobile, costmer_address, floor, aprt_num, know_sign, aria, aria_costn);
    
        new Deliviry_jfram(costmer_name, costmer_mobile, costmer_address, floor, aprt_num, know_sign, aria, aria_cost).setVisible(true);
        this.setVisible(false);
}
else{
jLabel_error.setText("أدخل جميع البيانات المطلوبة......!");
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField_customer_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_customer_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_customer_phoneActionPerformed

    private void jTextField_customer_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_customer_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_customer_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Costmer_Deliviry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Costmer_Deliviry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Costmer_Deliviry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Costmer_Deliviry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Costmer_Deliviry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_addnewaria_save;
    private javax.swing.JComboBox<String> jComboBox_allaria_cost;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_aria_added;
    private javax.swing.JLabel jLabel_error;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField_addnew_aria;
    private javax.swing.JTextField jTextField_addnew_ariacost;
    private javax.swing.JTextField jTextField_chosen_aria;
    private javax.swing.JTextField jTextField_chosen_cost;
    private javax.swing.JTextField jTextField_customer_address;
    private javax.swing.JTextField jTextField_customer_aprtment_num;
    private javax.swing.JTextField jTextField_customer_floor;
    private javax.swing.JTextField jTextField_customer_know_sign;
    private javax.swing.JTextField jTextField_customer_name;
    private javax.swing.JTextField jTextField_customer_phone;
    // End of variables declaration//GEN-END:variables
}
