/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurants_manager;

import DataBaseConn.sqldatabaseconn;
import java.awt.ComponentOrientation;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class Search_Costmer_Deliviry extends javax.swing.JFrame {

    /**
     * Creates new form Search_and_Add_Deliviry
     */
    public Search_Costmer_Deliviry() {
         this.setAlwaysOnTop(true);
         this.setUndecorated(true);
         this.setVisible(true);
         this.setResizable(false);
         initComponents();
         
//         Toolkit t = Toolkit.getDefaultToolkit();
//         int wid = (int) t.getScreenSize().getWidth();
//         int hid = (int) t.getScreenSize().getHeight();
//          this.setSize(wid , hid);
//        // this.setSize(1000 , 620);
//         // this.pack();
//         this.setLocationRelativeTo(null);
//         // this.setLocation(wid/2-this.getSize().width/2, hid/2-this.getSize().height/2);

 Frame_Size frame_Size = new Frame_Size();
         this.setSize(frame_Size.width(),frame_Size.height());
     
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_result = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton_cust_address = new javax.swing.JRadioButton();
        jRadioButton_cust_phone = new javax.swing.JRadioButton();
        jRadioButton_cust_name = new javax.swing.JRadioButton();
        jTextField_search = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jTextField_floor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_aprtment = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_aria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_phone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_address = new javax.swing.JTextField();
        jTextField_delv_cost = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_know_sign = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel_error = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton_start_order = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton_edit_customer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(15, 15, 15));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setText("_");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 0), null));
        jPanel2.setToolTipText("");

        jTable_result.setBackground(new java.awt.Color(51, 0, 0));
        jTable_result.setForeground(new java.awt.Color(255, 255, 255));
        jTable_result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "تكلفه التوصيل ", "المنطقة", "علامة مميزة", "رقم الشقة", "الدور", "العنوان", "الهاتف", "أسم العميل", "مسلسل"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_resultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_result);

        jPanel4.setBackground(new java.awt.Color(51, 0, 0));
        jPanel4.setForeground(new java.awt.Color(51, 0, 0));
        jPanel4.setToolTipText("");

        jRadioButton_cust_address.setBackground(new java.awt.Color(51, 0, 0));
        buttonGroup1.add(jRadioButton_cust_address);
        jRadioButton_cust_address.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButton_cust_address.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_cust_address.setText("بحث بعنوان العميل ");
        jRadioButton_cust_address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton_cust_address.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jRadioButton_cust_phone.setBackground(new java.awt.Color(51, 0, 0));
        buttonGroup1.add(jRadioButton_cust_phone);
        jRadioButton_cust_phone.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButton_cust_phone.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_cust_phone.setText("بحث برقم هاتف العميل");
        jRadioButton_cust_phone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton_cust_phone.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jRadioButton_cust_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_cust_phoneActionPerformed(evt);
            }
        });

        jRadioButton_cust_name.setBackground(new java.awt.Color(51, 0, 0));
        buttonGroup1.add(jRadioButton_cust_name);
        jRadioButton_cust_name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButton_cust_name.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_cust_name.setText("بحث بأسم العميل ");
        jRadioButton_cust_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton_cust_name.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jTextField_search.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_search.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_search.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_search.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 0), null));
        jTextField_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_searchActionPerformed(evt);
            }
        });
        jTextField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jTextField_search)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton_cust_address)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_cust_phone)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_cust_name)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_cust_phone)
                    .addComponent(jRadioButton_cust_address)
                    .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_cust_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 0), null));
        jPanel3.setToolTipText("");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("أسم العميل :");

        jTextField_name.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_name.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_name.setToolTipText("");
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyReleased(evt);
            }
        });

        jTextField_floor.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_floor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_floor.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_floor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_floor.setToolTipText("");
        jTextField_floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_floorActionPerformed(evt);
            }
        });
        jTextField_floor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_floorKeyReleased(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("الدور :");

        jTextField_aprtment.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_aprtment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_aprtment.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_aprtment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_aprtment.setToolTipText("");
        jTextField_aprtment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_aprtmentKeyReleased(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("رقم الشقة :");

        jTextField_aria.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_aria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_aria.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_aria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_aria.setToolTipText("");
        jTextField_aria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_ariaKeyReleased(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("المنطقة :");

        jTextField_phone.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_phone.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_phone.setToolTipText("");
        jTextField_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_phoneKeyReleased(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("الهاتف :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("العنوان :");

        jTextField_address.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_address.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_address.setToolTipText("");
        jTextField_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_addressKeyReleased(evt);
            }
        });

        jTextField_delv_cost.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_delv_cost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_delv_cost.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_delv_cost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_delv_cost.setText("0");
        jTextField_delv_cost.setToolTipText("");
        jTextField_delv_cost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_delv_costKeyReleased(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("تكلفة التوصيل :");

        jTextField_know_sign.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_know_sign.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_know_sign.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_know_sign.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_know_sign.setToolTipText("");
        jTextField_know_sign.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_know_signKeyReleased(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("علامة مميزة :");

        jLabel_error.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_error.setForeground(new java.awt.Color(153, 0, 0));
        jLabel_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_error.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_address)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 389, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addComponent(jTextField_know_sign))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_delv_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jTextField_aria))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(jLabel7)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jTextField_aprtment, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_floor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_error, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel6))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_floor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_aprtment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_aria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_delv_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_know_sign, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel7))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Safi_restaurants_manager/pics/person_search_icon.png"))); // NOI18N
        jLabel10.setText("بحث عن عميل");
        jLabel10.setToolTipText("");

        jPanel5.setBackground(new java.awt.Color(15, 15, 15));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 0), null));

        jButton_start_order.setBackground(new java.awt.Color(0, 153, 51));
        jButton_start_order.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_start_order.setForeground(new java.awt.Color(255, 255, 255));
        jButton_start_order.setText("أبدأ طلب");
        jButton_start_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_start_orderActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 51));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("أضافة عميل جديد");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton_edit_customer.setBackground(new java.awt.Color(0, 153, 51));
        jButton_edit_customer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_edit_customer.setForeground(new java.awt.Color(255, 255, 255));
        jButton_edit_customer.setText("تعديل");
        jButton_edit_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_edit_customerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_start_order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_edit_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_edit_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_start_order, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(10, 10, 10)
                        .addComponent(jButton1))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int rowcount =0;

int id ;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.setVisible(false);
   //  new Takeaway_jframe().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyReleased
String choss_state ="";
jLabel_error.setText("");
jButton_edit_customer.setEnabled(false);

if (jRadioButton_cust_name.isSelected()){choss_state = "costmer_name";}
if (jRadioButton_cust_phone.isSelected()){choss_state = "costmer_mobile";}
if (jRadioButton_cust_address.isSelected()){choss_state = "costmer_address";}

sqldatabaseconn conn = new sqldatabaseconn();
Statement s ;
ResultSet r ;

try{
    
     s =conn.connect().createStatement(ResultSet.TYPE_FORWARD_ONLY,ResultSet.CONCUR_READ_ONLY);
     r =s.executeQuery("select * from add_costmerdeliviry where "+choss_state+"  like "+"'"+jTextField_search.getText()+"%'");

     
     int rowcount =0;
   
            int databaserowcount = 1000 ; //r.getRow();//get coun of databaserows
            int tabelrowcount= jTable_result.getModel().getRowCount();//get count of table roes
            
            for(int j=tabelrowcount-1;j>=0;j--){
            DefaultTableModel dm =(DefaultTableModel)jTable_result.getModel();
            dm.removeRow(j);
            }
  
           for(int i=0;i<databaserowcount;i++){
              DefaultTableModel dm=(DefaultTableModel)jTable_result.getModel();
              dm.addRow(new Object[0]);
            } 
           
           while(r.next())
            {
                jTable_result.setValueAt(r.getString("_id"), rowcount,8);
               jTable_result.setValueAt(r.getString("costmer_name"), rowcount,7);
               jTable_result.setValueAt(r.getString("costmer_mobile"), rowcount,6);
                jTable_result.setValueAt(r.getString("costmer_address"), rowcount,5);                
                jTable_result.setValueAt(r.getString("floor"), rowcount,4);
                jTable_result.setValueAt(r.getString("aprt_num"), rowcount,3);
                jTable_result.setValueAt(r.getString("know_sign"), rowcount,2);
                jTable_result.setValueAt(r.getString("aria"), rowcount,1);
                jTable_result.setValueAt(r.getString("aria_cost"), rowcount,0);
           
                rowcount ++;          
            }
           
}
catch(Exception e){System.out.println(e);}
   
    }//GEN-LAST:event_jTextField_searchKeyReleased

    private void jTable_resultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_resultMouseClicked
     
int colum_id = 8;
int row_id = jTable_result.getSelectedRow();
String cust_ids = jTable_result.getModel().getValueAt(row_id, colum_id).toString();
id = Integer.parseInt(cust_ids);
        
int colum_name = 7;
int row_name = jTable_result.getSelectedRow();
String cust_name = jTable_result.getModel().getValueAt(row_name, colum_name).toString();

int colum_phone = 6;
int row_phone = jTable_result.getSelectedRow();
String cust_phone = jTable_result.getModel().getValueAt(row_phone, colum_phone).toString();

int colum_address = 5;
int row_address = jTable_result.getSelectedRow();
String cust_address = jTable_result.getModel().getValueAt(row_address, colum_address).toString();

int colum_floor = 4;
int row_floor = jTable_result.getSelectedRow();
String cust_floor = jTable_result.getModel().getValueAt(row_floor, colum_floor).toString();

int colum_aprt_num = 3;
int row_aprt_num = jTable_result.getSelectedRow();
String cust_aprt_num = jTable_result.getModel().getValueAt(row_aprt_num, colum_aprt_num).toString();

int colum_know_sign = 2;
int row_know_sign = jTable_result.getSelectedRow();
String cust_know_sign = jTable_result.getModel().getValueAt(row_know_sign, colum_know_sign).toString();

int colum_aria = 1;
int row_aria = jTable_result.getSelectedRow();
String cust_aria = jTable_result.getModel().getValueAt(row_aria, colum_aria).toString();

int colum_aria_cost = 0;
int row_aria_cost = jTable_result.getSelectedRow();
String cust_aria_cost = jTable_result.getModel().getValueAt(row_aria_cost, colum_aria_cost).toString();

jTextField_name.setText(cust_name);
jTextField_phone.setText(cust_phone);
jTextField_address.setText(cust_address);
jTextField_aprtment.setText(cust_aprt_num);
jTextField_floor.setText(cust_floor);
jTextField_aria.setText(cust_aria);
jTextField_delv_cost.setText(cust_aria_cost);
jTextField_know_sign.setText(cust_know_sign);

 
 
      String costmer_name =   jTextField_name.getText();
      String costmer_mobile =  jTextField_phone.getText();
      String costmer_address = jTextField_address.getText();
      String aprt_num =  jTextField_aprtment.getText();
      String floor =  jTextField_floor.getText();
      String aria =  jTextField_aria.getText();
      String know_sign =   jTextField_know_sign.getText();
      String aria_cost =  jTextField_delv_cost.getText();
     
        
       if(!costmer_name.equals("")&&!costmer_mobile.equals("")&&!costmer_address.equals("")&&!aprt_num.equals("")&&
   !floor.equals("")&&!aria.equals("")&&!know_sign.equals("")&&!aria_cost.equals("")){  
      jButton_start_order.setEnabled(true);
       
       }
       else{
       jLabel_error.setText("بيانات العميل ناقصة عدل البيانات ثم أبحث من جديد");
       }
 
 
      
        
    }//GEN-LAST:event_jTable_resultMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       jRadioButton_cust_phone.setSelected(true);
        jButton_edit_customer.setEnabled(false);
        jButton_start_order.setEnabled(false);
        jTextField_name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
 jTextField_address.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
 jTextField_know_sign.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       
    }//GEN-LAST:event_formWindowActivated

    private void jButton_edit_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_edit_customerActionPerformed
        
      String costmer_name =   jTextField_name.getText();
      String costmer_mobile =  jTextField_phone.getText();
      String costmer_mobile2 =  jTextField_phone.getText();
      String costmer_address = jTextField_address.getText();
      String aprt_num =  jTextField_aprtment.getText();
      String floor =  jTextField_floor.getText();
      String aria =  jTextField_aria.getText();
      String know_sign =   jTextField_know_sign.getText();
      String aria_cost =  jTextField_delv_cost.getText();
      int aria_costn = Integer.parseInt(aria_cost);
        
       if(!costmer_name.equals("")&&!costmer_mobile.equals("")&&!costmer_address.equals("")&&!aprt_num.equals("")&&
   !floor.equals("")&&!aria.equals("")&&!know_sign.equals("")&&!aria_cost.equals("")){  
      
        sqldatabaseconn update_customer_data = new sqldatabaseconn();
        update_customer_data.update_customer_data("add_costmerdeliviry", costmer_name, costmer_mobile, costmer_mobile2, costmer_address, floor, aprt_num, know_sign, aria,aria_costn,id);
        jLabel_error.setText("تم التعديل بنجاح");
       }
       else{
       jLabel_error.setText("أدخل جميع البيانات ......!");
       }
    }//GEN-LAST:event_jButton_edit_customerActionPerformed

    private void jTextField_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyReleased
      jButton_edit_customer.setEnabled(true);
    }//GEN-LAST:event_jTextField_nameKeyReleased

    private void jTextField_phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phoneKeyReleased
      jButton_edit_customer.setEnabled(true);
    }//GEN-LAST:event_jTextField_phoneKeyReleased

    private void jTextField_addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_addressKeyReleased
       jButton_edit_customer.setEnabled(true);
    }//GEN-LAST:event_jTextField_addressKeyReleased

    private void jTextField_floorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_floorKeyReleased
       jButton_edit_customer.setEnabled(true);
    }//GEN-LAST:event_jTextField_floorKeyReleased

    private void jTextField_aprtmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_aprtmentKeyReleased
      jButton_edit_customer.setEnabled(true);
    }//GEN-LAST:event_jTextField_aprtmentKeyReleased

    private void jTextField_ariaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ariaKeyReleased
        jButton_edit_customer.setEnabled(true);
    }//GEN-LAST:event_jTextField_ariaKeyReleased

    private void jTextField_delv_costKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_delv_costKeyReleased
         jButton_edit_customer.setEnabled(true);
    }//GEN-LAST:event_jTextField_delv_costKeyReleased

    private void jTextField_know_signKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_know_signKeyReleased
        jButton_edit_customer.setEnabled(true);
    }//GEN-LAST:event_jTextField_know_signKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new Add_Costmer_Deliviry().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_start_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_start_orderActionPerformed

        String costmer_name = jTextField_name.getText();
        String costmer_mobile =  jTextField_phone.getText();
        String costmer_address = jTextField_address.getText();
        String aprt_num =  jTextField_aprtment.getText();
        String floor =  jTextField_floor.getText();
        String aria =  jTextField_aria.getText();
        String know_sign =   jTextField_know_sign.getText();
        String aria_cost =  jTextField_delv_cost.getText();
       
            if(!costmer_name.equals("")&&!costmer_mobile.equals("")&&!costmer_address.equals("")&&!aprt_num.equals("")&&
               !floor.equals("")&&!aria.equals("")&&!know_sign.equals("")&&!aria_cost.equals("")){  
      
       new Deliviry_jfram(costmer_name, costmer_mobile, costmer_address, floor, aprt_num, know_sign, aria, aria_cost).setVisible(true);
        this.setVisible(false);
          
       }
       else{
       jLabel_error.setText("أدخل جميع البيانات ......!");
       }
        
       
    }//GEN-LAST:event_jButton_start_orderActionPerformed

    private void jTextField_floorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_floorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_floorActionPerformed

    private void jRadioButton_cust_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_cust_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_cust_phoneActionPerformed

    private void jTextField_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchActionPerformed
   
    
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Costmer_Deliviry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Costmer_Deliviry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Costmer_Deliviry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Costmer_Deliviry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Costmer_Deliviry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_edit_customer;
    private javax.swing.JButton jButton_start_order;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_error;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton_cust_address;
    private javax.swing.JRadioButton jRadioButton_cust_name;
    private javax.swing.JRadioButton jRadioButton_cust_phone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_result;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_aprtment;
    private javax.swing.JTextField jTextField_aria;
    private javax.swing.JTextField jTextField_delv_cost;
    private javax.swing.JTextField jTextField_floor;
    private javax.swing.JTextField jTextField_know_sign;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables
}
