/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurants_manager;

import DataBaseConn.sqldatabaseconn;
import java.awt.ComponentOrientation;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class Search_Transaction extends javax.swing.JFrame {

    /**
     * Creates new form Search_and_Add_Deliviry
     */
    public Search_Transaction(String supplier_phone) {
         this.setAlwaysOnTop(true);
         this.setUndecorated(true);
         this.setVisible(true);
         this.setResizable(false);
         initComponents();
         
//         Toolkit t = Toolkit.getDefaultToolkit();
//         int wid = (int) t.getScreenSize().getWidth();
//         int hid = (int) t.getScreenSize().getHeight();
//          this.setSize(wid , hid);
       //  this.setSize(1360 , 768);
         // this.pack();
      //   this.setLocationRelativeTo(null);
         // this.setLocation(wid/2-this.getSize().width/2, hid/2-this.getSize().height/2);
         
          Frame_Size frame_Size = new Frame_Size();
         this.setSize(frame_Size.width(),frame_Size.height());
     
         sended_supplier_phone = supplier_phone ;
     
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_result = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel_error = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_supplier_name = new javax.swing.JTextField();
        jTextField_supplier_hint = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_supplier_phone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_supplier_company = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_type_of_goods = new javax.swing.JTextField();
        jTextField_he_want = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_i_want = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_transaction_date = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_transaction_hint = new javax.swing.JTextField();
        jButton_end_delete_transaction = new javax.swing.JButton();
        jButton_edit_transaction = new javax.swing.JButton();
        jTextField_transaction_total = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(15, 15, 15));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 900));

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setText("_");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 0), null));
        jPanel2.setToolTipText("");

        jTable_result.setBackground(new java.awt.Color(51, 0, 0));
        jTable_result.setForeground(new java.awt.Color(255, 255, 255));
        jTable_result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ملحوظه عن التعامل", "تاريخ التعامل", "دائن (عليه)", "مدين (له)", "نوع البضاعة", "ملحوظة عن المورد", "اسم الشركة", "الهاتف", "اسم المورد", "مسلسل"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_resultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_result);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 0), null));
        jPanel3.setToolTipText("");

        jLabel_error.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_error.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_error.setToolTipText("");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("أسم المورد :");

        jTextField_supplier_name.setEditable(false);
        jTextField_supplier_name.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_supplier_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_supplier_name.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_supplier_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_supplier_name.setToolTipText("");
        jTextField_supplier_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_supplier_nameKeyReleased(evt);
            }
        });

        jTextField_supplier_hint.setEditable(false);
        jTextField_supplier_hint.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_supplier_hint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_supplier_hint.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_supplier_hint.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_supplier_hint.setToolTipText("");
        jTextField_supplier_hint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_supplier_hintActionPerformed(evt);
            }
        });
        jTextField_supplier_hint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_supplier_hintKeyReleased(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ملحوظة :");

        jTextField_supplier_phone.setEditable(false);
        jTextField_supplier_phone.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_supplier_phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_supplier_phone.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_supplier_phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_supplier_phone.setToolTipText("");
        jTextField_supplier_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_supplier_phoneKeyReleased(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("الهاتف :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("اسم الشركة :");

        jTextField_supplier_company.setEditable(false);
        jTextField_supplier_company.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_supplier_company.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_supplier_company.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_supplier_company.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_supplier_company.setToolTipText("");
        jTextField_supplier_company.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_supplier_companyKeyReleased(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("نوع البضاعة :");

        jTextField_type_of_goods.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_type_of_goods.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_type_of_goods.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_type_of_goods.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_type_of_goods.setToolTipText("");
        jTextField_type_of_goods.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_type_of_goodsKeyReleased(evt);
            }
        });

        jTextField_he_want.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_he_want.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_he_want.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_he_want.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_he_want.setToolTipText("");
        jTextField_he_want.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_he_wantKeyReleased(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("مدين (له) :");

        jTextField_i_want.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_i_want.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_i_want.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_i_want.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_i_want.setToolTipText("");
        jTextField_i_want.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_i_wantKeyReleased(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("دائن(عليه) :");

        jTextField_transaction_date.setEditable(false);
        jTextField_transaction_date.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_transaction_date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_transaction_date.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_transaction_date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_transaction_date.setToolTipText("");
        jTextField_transaction_date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_transaction_dateKeyReleased(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("تاريخ التعامل :");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ملحوظة عن التعامل :");

        jTextField_transaction_hint.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_transaction_hint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_transaction_hint.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_transaction_hint.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_transaction_hint.setToolTipText("");
        jTextField_transaction_hint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_transaction_hintActionPerformed(evt);
            }
        });
        jTextField_transaction_hint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_transaction_hintKeyReleased(evt);
            }
        });

        jButton_end_delete_transaction.setBackground(new java.awt.Color(0, 153, 51));
        jButton_end_delete_transaction.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_end_delete_transaction.setForeground(new java.awt.Color(255, 255, 255));
        jButton_end_delete_transaction.setText("أنهاء و حذف المعاملة");
        jButton_end_delete_transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_end_delete_transactionActionPerformed(evt);
            }
        });

        jButton_edit_transaction.setBackground(new java.awt.Color(0, 153, 51));
        jButton_edit_transaction.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_edit_transaction.setForeground(new java.awt.Color(255, 255, 255));
        jButton_edit_transaction.setText("تعديل");
        jButton_edit_transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_edit_transactionActionPerformed(evt);
            }
        });

        jTextField_transaction_total.setEditable(false);
        jTextField_transaction_total.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_transaction_total.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_transaction_total.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_transaction_total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_transaction_total.setToolTipText("");
        jTextField_transaction_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_transaction_totalKeyReleased(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("صافى مبلغ التعامل :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_transaction_hint, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_supplier_company, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_supplier_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_supplier_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jTextField_supplier_hint, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 371, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addComponent(jTextField_transaction_date))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_transaction_total, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_i_want, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_he_want, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_type_of_goods, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jButton_end_delete_transaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_edit_transaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_error, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_supplier_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_supplier_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_supplier_company, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_supplier_hint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_type_of_goods, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_he_want, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_i_want, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField_transaction_total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField_transaction_date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_transaction_hint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton_edit_transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_end_delete_transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel10.setBackground(new java.awt.Color(51, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Safi_restaurants_manager/pics/tamolat_big_icon.png"))); // NOI18N
        jLabel10.setText("معاملات موردين");
        jLabel10.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1576, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int rowcount =0;

int id ;

String sended_supplier_phone = "" ;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.setVisible(false);
   //  new Takeaway_jframe().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable_resultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_resultMouseClicked
     
int colum_id = 9;
int row_id = jTable_result.getSelectedRow();
String cust_ids = jTable_result.getModel().getValueAt(row_id, colum_id).toString();
id = Integer.parseInt(cust_ids);
        
int colum_name = 8;
int row_name = jTable_result.getSelectedRow();
String cust_name = jTable_result.getModel().getValueAt(row_name, colum_name).toString();

int colum_phone = 7;
int row_phone = jTable_result.getSelectedRow();
String cust_phone = jTable_result.getModel().getValueAt(row_phone, colum_phone).toString();

int colum_company = 6;
int row_company = jTable_result.getSelectedRow();
String cust_company = jTable_result.getModel().getValueAt(row_company, colum_company).toString();

int colum_hint = 5;
int row_hint = jTable_result.getSelectedRow();
String cust_hint = jTable_result.getModel().getValueAt(row_hint, colum_hint).toString();

int colum_goods = 4;
int row_goods = jTable_result.getSelectedRow();
String cust_goods = jTable_result.getModel().getValueAt(row_goods, colum_goods).toString();

int colum_he = 3;
int row_he = jTable_result.getSelectedRow();
String cust_he = jTable_result.getModel().getValueAt(row_he, colum_he).toString();

int colum_i = 2;
int row_i = jTable_result.getSelectedRow();
String cust_i = jTable_result.getModel().getValueAt(row_i, colum_i).toString();

int colum_date = 1;
int row_date = jTable_result.getSelectedRow();
String cust_date = jTable_result.getModel().getValueAt(row_date, colum_date).toString();

int colum_trans_hint = 0;
int row_trans_hint = jTable_result.getSelectedRow();
String cust_trans_hint = jTable_result.getModel().getValueAt(row_trans_hint, colum_trans_hint).toString();



jTextField_supplier_name.setText(cust_name);
jTextField_supplier_phone.setText(cust_phone);
jTextField_supplier_company.setText(cust_company);
jTextField_supplier_hint.setText(cust_hint);
jTextField_type_of_goods.setText(cust_goods);
jTextField_he_want.setText(cust_he);
jTextField_i_want.setText(cust_i);
jTextField_transaction_date.setText(cust_date);
jTextField_transaction_hint.setText(cust_trans_hint);

jButton_end_delete_transaction.setEnabled(true);


int total = Integer.parseInt(cust_i)-Integer.parseInt(cust_he);
jTextField_transaction_total.setText(Integer.toString(Math.abs(total)));


 
 
        String supplier_name = jTextField_supplier_name.getText();
        String supplier_phone =  jTextField_supplier_phone.getText();
        String supplier_company = jTextField_supplier_company.getText();       
        String supplier_hint =  jTextField_supplier_hint.getText();
        String type_of_goods =  jTextField_type_of_goods.getText();
        String he_want =  jTextField_he_want.getText();
        String i_want =  jTextField_i_want.getText();
        String transaction_date =  jTextField_transaction_date.getText();
        String transaction_hint =  jTextField_transaction_hint.getText();
     
     
        
//       if(!supplier_name.equals("")&&!supplier_phone.equals("")&&!supplier_company.equals("")&&!supplier_hint.equals("")
//          &&!type_of_goods.equals("")&&!he_want.equals("")&&!i_want.equals("")&&!transaction_date.equals("")&&!transaction_hint.equals("")){  
//      jButton_edit_transaction.setEnabled(true);
//      jButton_end_delete_transaction.setEnabled(true);
//       
//       }
//       else{
//       jLabel_error.setText("بيانات التعامل ناقصة عدل البيانات");
//       }
 
 
      
        
    }//GEN-LAST:event_jTable_resultMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     
        jButton_edit_transaction.setEnabled(false);
      jButton_end_delete_transaction.setEnabled(false);
        jTextField_supplier_name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
 jTextField_supplier_company.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
 
jLabel_error.setText("");




sqldatabaseconn conn = new sqldatabaseconn();
Statement s ;
ResultSet r ;

try{
    
     s =conn.connect().createStatement(ResultSet.TYPE_FORWARD_ONLY,ResultSet.CONCUR_READ_ONLY);
     if(sended_supplier_phone.equals("")){
     r =s.executeQuery("select * from supplier_dealings ");
     }
     else
     {
     r =s.executeQuery("select * from supplier_dealings where supplier_phone  like "+"'"+sended_supplier_phone+"%'");
     }

     
     int rowcount =0;
   
            int databaserowcount = 1000 ; //r.getRow();//get coun of databaserows
            int tabelrowcount= jTable_result.getModel().getRowCount();//get count of table roes
            
            for(int j=tabelrowcount-1;j>=0;j--){
            DefaultTableModel dm =(DefaultTableModel)jTable_result.getModel();
            dm.removeRow(j);
            }
  
           for(int i=0;i<databaserowcount;i++){
              DefaultTableModel dm=(DefaultTableModel)jTable_result.getModel();
              dm.addRow(new Object[0]);
            } 
           
           while(r.next())
            {
                jTable_result.setValueAt(r.getString("_id"), rowcount,9);
               jTable_result.setValueAt(r.getString("supplier_name"), rowcount,8);
               jTable_result.setValueAt(r.getString("supplier_phone"), rowcount,7);
                jTable_result.setValueAt(r.getString("supplier_company"), rowcount,6);                
                jTable_result.setValueAt(r.getString("supplier_hint"), rowcount,5);
                 jTable_result.setValueAt(r.getString("type_of_goods"), rowcount,4);
               jTable_result.setValueAt(r.getString("he_want"), rowcount,3);
               jTable_result.setValueAt(r.getString("i_want"), rowcount,2);
                jTable_result.setValueAt(r.getString("transaction_date"), rowcount,1);                
                jTable_result.setValueAt(r.getString("transaction_hint"), rowcount,0);
               
               
           
                rowcount ++;          
            }
           
}
catch(Exception e){System.out.println(e);}
       
    }//GEN-LAST:event_formWindowActivated

    private void jButton_edit_transactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_edit_transactionActionPerformed
        
      String type_of_goods =   jTextField_type_of_goods.getText();
      String he_want =  jTextField_he_want.getText();
      String i_want =  jTextField_i_want.getText();
      String transaction_hint = jTextField_transaction_hint.getText();
      
     
      
      
      
     
        
       if(!type_of_goods.equals("")&&!he_want.equals("")&&!i_want.equals("")&&!transaction_hint.equals("")&&test_num(i_want)&&test_num(he_want)){  
      
        sqldatabaseconn update_transaction_data = new sqldatabaseconn();
        update_transaction_data.update_transaction_data("supplier_dealings", type_of_goods, he_want, i_want, transaction_hint,id);
        jLabel_error.setText("تم التعديل بنجاح");
        
        
         
        jButton_edit_transaction.setEnabled(false);
      jButton_end_delete_transaction.setEnabled(false);
        jTextField_supplier_name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
 jTextField_supplier_company.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
 
jLabel_error.setText("");




sqldatabaseconn conn = new sqldatabaseconn();
Statement s ;
ResultSet r ;

try{
    
     s =conn.connect().createStatement(ResultSet.TYPE_FORWARD_ONLY,ResultSet.CONCUR_READ_ONLY);
     if(sended_supplier_phone.equals("")){
     r =s.executeQuery("select * from supplier_dealings ");
     }
     else
     {
     r =s.executeQuery("select * from supplier_dealings where supplier_phone  like "+"'"+sended_supplier_phone+"%'");
     }

     
     int rowcount =0;
   
            int databaserowcount = 1000 ; //r.getRow();//get coun of databaserows
            int tabelrowcount= jTable_result.getModel().getRowCount();//get count of table roes
            
            for(int j=tabelrowcount-1;j>=0;j--){
            DefaultTableModel dm =(DefaultTableModel)jTable_result.getModel();
            dm.removeRow(j);
            }
  
           for(int i=0;i<databaserowcount;i++){
              DefaultTableModel dm=(DefaultTableModel)jTable_result.getModel();
              dm.addRow(new Object[0]);
            } 
           
           while(r.next())
            {
                jTable_result.setValueAt(r.getString("_id"), rowcount,9);
               jTable_result.setValueAt(r.getString("supplier_name"), rowcount,8);
               jTable_result.setValueAt(r.getString("supplier_phone"), rowcount,7);
                jTable_result.setValueAt(r.getString("supplier_company"), rowcount,6);                
                jTable_result.setValueAt(r.getString("supplier_hint"), rowcount,5);
                 jTable_result.setValueAt(r.getString("type_of_goods"), rowcount,4);
               jTable_result.setValueAt(r.getString("he_want"), rowcount,3);
               jTable_result.setValueAt(r.getString("i_want"), rowcount,2);
                jTable_result.setValueAt(r.getString("transaction_date"), rowcount,1);                
                jTable_result.setValueAt(r.getString("transaction_hint"), rowcount,0);
               
               
           
                rowcount ++;          
            }
           
}
catch(Exception e){System.out.println(e);}
        
        
       }
       else{
       jLabel_error.setText("ادخل جميع البيانات بطريقه صحيحة و تحقق من عدم كتابه حروف فى خانات الأرقام");
       }
    }//GEN-LAST:event_jButton_edit_transactionActionPerformed

    private void jTextField_supplier_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_supplier_nameKeyReleased
      
    }//GEN-LAST:event_jTextField_supplier_nameKeyReleased

    private void jTextField_supplier_phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_supplier_phoneKeyReleased
    }//GEN-LAST:event_jTextField_supplier_phoneKeyReleased

    private void jTextField_supplier_companyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_supplier_companyKeyReleased
    }//GEN-LAST:event_jTextField_supplier_companyKeyReleased

    private void jTextField_supplier_hintKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_supplier_hintKeyReleased
    }//GEN-LAST:event_jTextField_supplier_hintKeyReleased

    private void jTextField_supplier_hintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_supplier_hintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_supplier_hintActionPerformed

    private void jButton_end_delete_transactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_end_delete_transactionActionPerformed
        
        sqldatabaseconn delete_trans = new sqldatabaseconn();
        delete_trans.delete("supplier_dealings", id);
        
        
        jTextField_supplier_name.setText("");
jTextField_supplier_phone.setText("");
jTextField_supplier_company.setText("");
jTextField_supplier_hint.setText("");
jTextField_type_of_goods.setText("");
jTextField_he_want.setText("");
jTextField_i_want.setText("");
jTextField_transaction_date.setText("");
jTextField_transaction_hint.setText("");
        
        
           jButton_edit_transaction.setEnabled(false);
      jButton_end_delete_transaction.setEnabled(false);
        jTextField_supplier_name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
 jTextField_supplier_company.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
 
jLabel_error.setText("");


 DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        jTextField_transaction_date.setText(dtf.format(now));





sqldatabaseconn conn = new sqldatabaseconn();
Statement s ;
ResultSet r ;

try{
    
     s =conn.connect().createStatement(ResultSet.TYPE_FORWARD_ONLY,ResultSet.CONCUR_READ_ONLY);
     if(sended_supplier_phone.equals("")){
     r =s.executeQuery("select * from supplier_dealings ");
     }
     else
     {
     r =s.executeQuery("select * from supplier_dealings where supplier_phone  like "+"'"+sended_supplier_phone+"%'");
     }

     
     int rowcount =0;
   
            int databaserowcount = 1000 ; //r.getRow();//get coun of databaserows
            int tabelrowcount= jTable_result.getModel().getRowCount();//get count of table roes
            
            for(int j=tabelrowcount-1;j>=0;j--){
            DefaultTableModel dm =(DefaultTableModel)jTable_result.getModel();
            dm.removeRow(j);
            }
  
           for(int i=0;i<databaserowcount;i++){
              DefaultTableModel dm=(DefaultTableModel)jTable_result.getModel();
              dm.addRow(new Object[0]);
            } 
           
           while(r.next())
            {
                jTable_result.setValueAt(r.getString("_id"), rowcount,9);
               jTable_result.setValueAt(r.getString("supplier_name"), rowcount,8);
               jTable_result.setValueAt(r.getString("supplier_phone"), rowcount,7);
                jTable_result.setValueAt(r.getString("supplier_company"), rowcount,6);                
                jTable_result.setValueAt(r.getString("supplier_hint"), rowcount,5);
                 jTable_result.setValueAt(r.getString("type_of_goods"), rowcount,4);
               jTable_result.setValueAt(r.getString("he_want"), rowcount,3);
               jTable_result.setValueAt(r.getString("i_want"), rowcount,2);
                jTable_result.setValueAt(r.getString("transaction_date"), rowcount,1);                
                jTable_result.setValueAt(r.getString("transaction_hint"), rowcount,0);
               
               
           
                rowcount ++;          
            }
           
}
catch(Exception e){System.out.println(e);}
        
        
    }//GEN-LAST:event_jButton_end_delete_transactionActionPerformed

    private void jTextField_type_of_goodsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_type_of_goodsKeyReleased
jButton_edit_transaction.setEnabled(true);
    }//GEN-LAST:event_jTextField_type_of_goodsKeyReleased

    private void jTextField_he_wantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_he_wantKeyReleased
        jButton_edit_transaction.setEnabled(true);
        
        int total = Integer.parseInt(jTextField_i_want.getText())-Integer.parseInt(jTextField_he_want.getText());
        jTextField_transaction_total.setText(Integer.toString(Math.abs(total)));
    }//GEN-LAST:event_jTextField_he_wantKeyReleased

    private void jTextField_i_wantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_i_wantKeyReleased
        jButton_edit_transaction.setEnabled(true);
        
          int total = Integer.parseInt(jTextField_i_want.getText())-Integer.parseInt(jTextField_he_want.getText());
        jTextField_transaction_total.setText(Integer.toString(Math.abs(total)));
    }//GEN-LAST:event_jTextField_i_wantKeyReleased

    private void jTextField_transaction_dateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_transaction_dateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_transaction_dateKeyReleased

    private void jTextField_transaction_hintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_transaction_hintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_transaction_hintActionPerformed

    private void jTextField_transaction_hintKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_transaction_hintKeyReleased
        jButton_edit_transaction.setEnabled(true);
        
    }//GEN-LAST:event_jTextField_transaction_hintKeyReleased

    private void jTextField_transaction_totalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_transaction_totalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_transaction_totalKeyReleased
   
    
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Transaction("").setVisible(true);
            }
        });
    }
    
     private boolean test_num(String text) {
      try {
         Integer.parseInt(text);
         return true;
      } catch (NumberFormatException e) {
         return false;
      }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_edit_transaction;
    private javax.swing.JButton jButton_end_delete_transaction;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_error;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_result;
    private javax.swing.JTextField jTextField_he_want;
    private javax.swing.JTextField jTextField_i_want;
    private javax.swing.JTextField jTextField_supplier_company;
    private javax.swing.JTextField jTextField_supplier_hint;
    private javax.swing.JTextField jTextField_supplier_name;
    private javax.swing.JTextField jTextField_supplier_phone;
    private javax.swing.JTextField jTextField_transaction_date;
    private javax.swing.JTextField jTextField_transaction_hint;
    private javax.swing.JTextField jTextField_transaction_total;
    private javax.swing.JTextField jTextField_type_of_goods;
    // End of variables declaration//GEN-END:variables
}
